fix: replace debug to console.warn
plaidev/cookie pull request #2
Opened 2019-07-03 12:07 UTC by TatsuyaKITABORI

https://github.com/t5kz/cookie/pull/2

間違えて別のリポジトリにPR作ってたからこっちで作り直し

2019-07-03 12:08 UTC, otolab requested changes

2019-07-03 12:08 UTC, otolab commented on index.js
> +    console.warn('error `parse(' + value +')` - ' + e)
細かいけど、encodeだね。

2019-07-03 12:08 UTC, otolab commented on index.js
> +    console.warn('error `parse(' + value +')` - ' + e)
こっちはdecode

2019-07-03 12:11 UTC, TatsuyaKITABORI commented on index.js
> +    console.warn('error `parse(' + value +')` - ' + e)
ああごめんなさいコピペしてました
直します

2019-07-03 12:46 UTC, otolab approved these changes

2019-07-03 12:46 UTC, merged

2019-07-03 12:46 UTC, otolab commented
@TatsuyaKITABORI ありがとー。

2019-07-03 12:47 UTC, TatsuyaKITABORI commented
確認してみます

2019-07-10 17:52 UTC, otolab commented
https://github.com/plaidev/karte-io/issues/36300